# -*- coding: utf-8 -*-
"""Veri_Bilimi_Proje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzajazfIpYApFsVduhrxy3v6JHqLcX06
"""

# 1. KÜTÜPHANE YÜKLEMESİ
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, roc_auc_score, roc_curve)

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

import warnings
warnings.filterwarnings("ignore")

# 2. VERİ YÜKLEMESİ
df = pd.read_csv("Occupancy_Estimation.csv")

# Time sütununu düşür (saat/dakika bilgisi, öznitelik değil)
df = df.drop(columns=["Time"], errors="ignore")
df.columns = df.columns.str.strip()

print("Sütun adları:", df.columns.tolist())
print("=" * 60)
print("VERİ SETİ GENEL BİLGİSİ")
print("=" * 60)
print(f"Satır Sayısı  : {df.shape[0]}")
print(f"Sütun Sayısı  : {df.shape[1]}")
print(f"\nSınıf Dağılımı (Odadaki Kişi Sayısı):\n{df['Room_Occupancy_Count'].value_counts().sort_index()}")
print(f"\nEksik Değer Sayısı:\n{df.isnull().sum()}")
print(f"\nTemel İstatistikler:\n{df.describe()}")

# 3. GÖRSELLEŞTİRME — Öznitelik Dağılımları
# En ayırt edici 6 sensörü seçiyoruz
features_to_plot = ["S1_Temp", "S1_Light", "S2_Light",
                    "S5_CO2", "S5_CO2_Slope", "S1_Sound"]

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
fig.suptitle("Öznitelik Dağılımları — Sınıf Bazında (0–3 Kişi)",
             fontsize=14, fontweight="bold")

colors = ["#2196F3", "#4CAF50", "#FF9800", "#F44336"]
labels = ["0 Kişi", "1 Kişi", "2 Kişi", "3 Kişi"]

for i, feat in enumerate(features_to_plot):
    ax = axes[i // 3][i % 3]
    for cls, color, lbl in zip([0, 1, 2, 3], colors, labels):
        subset = df[df["Room_Occupancy_Count"] == cls][feat]
        ax.hist(subset, bins=35, alpha=0.55, color=color, label=lbl, density=True)
    ax.set_title(feat, fontsize=11, fontweight="bold")
    ax.set_xlabel(feat)
    ax.set_ylabel("Yoğunluk")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig("ozellik_dagilimi.png", dpi=150, bbox_inches="tight")
plt.show()
print("[✓] Görsel kaydedildi: ozellik_dagilimi.png")

# 4. KORELASYON MATRİSİ
fig_corr, ax = plt.subplots(figsize=(14, 11))
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm",
            ax=ax, linewidths=0.4, square=True, cbar=True,
            annot_kws={"size": 7})
ax.set_title("Korelasyon Matrisi", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("korelasyon_matrisi.png", dpi=150, bbox_inches="tight")
plt.show()
print("[✓] Görsel kaydedildi: korelasyon_matrisi.png")

# 5. ÖN İŞLEME
X = df.drop(["Room_Occupancy_Count", "Date"], axis=1)
y = df["Room_Occupancy_Count"]

# Eğitim / Test ayrımı — %80 / %20, stratify ile sınıf dengesi korunur
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print(f"\nEğitim seti : {X_train.shape[0]} örnek")
print(f"Test  seti  : {X_test.shape[0]} örnek")
print(f"Öznitelik sayısı: {X.shape[1]}")

# 6. ALGORİTMA KARŞILAŞTIRMASI
models = {
    "Random Forest"         : RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1),
    "Gradient Boosting"     : GradientBoostingClassifier(n_estimators=150, learning_rate=0.1,
                                                          max_depth=5, random_state=42),
    "Karar Ağacı"           : DecisionTreeClassifier(max_depth=10, random_state=42),
    "K-En Yakın Komşu"      : KNeighborsClassifier(n_neighbors=7, metric="euclidean"),
    "Lojistik Regresyon"    : LogisticRegression(max_iter=1000, C=1.0, random_state=42,
                                                  multi_class="multinomial", solver="lbfgs"),
    "Naive Bayes"           : GaussianNB(),
    "Destek Vektör Makinesi": SVC(kernel="rbf", C=10, gamma="scale",
                                   probability=True, random_state=42,
                                   decision_function_shape="ovr"),
    "Yapay Sinir Ağı"       : MLPClassifier(hidden_layer_sizes=(128, 64, 32), max_iter=300,
                                             activation="relu", random_state=42,
                                             early_stopping=True),
}

scaled_models = {"K-En Yakın Komşu", "Lojistik Regresyon",
                 "Destek Vektör Makinesi", "Yapay Sinir Ağı"}

# Çok sınıflı ROC-AUC: one-vs-rest (ovr) + macro ortalama
classes = sorted(y.unique())   # [0, 1, 2, 3]

results = {}
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("\n" + "=" * 60)
print("MODEL EĞİTİM VE DEĞERLENDİRME SONUÇLARI")
print("=" * 60)

for name, model in models.items():
    use_scaled = name in scaled_models
    Xtr  = X_train_scaled if use_scaled else X_train
    Xte  = X_test_scaled  if use_scaled else X_test
    Xfull = scaler.transform(X) if use_scaled else X

    model.fit(Xtr, y_train)
    y_pred = model.predict(Xte)
    y_prob = model.predict_proba(Xte)          # shape: (n_samples, 4)

    acc    = accuracy_score(y_test, y_pred)
    # Çok sınıflı ROC-AUC — ovr + macro
    roc    = roc_auc_score(y_test, y_prob, multi_class="ovr", average="macro")
    cv_acc = cross_val_score(model, Xfull, y, cv=cv, scoring="accuracy").mean()

    results[name] = {
        "Test Doğruluğu (%)": round(acc * 100, 2),
        "ROC-AUC (macro)":    round(roc, 4),
        "CV Doğruluğu (%)":   round(cv_acc * 100, 2),
    }
    print(f"\n{name}")
    print(f"  Test Doğruluğu : %{acc*100:.2f}")
    print(f"  ROC-AUC (macro): {roc:.4f}")
    print(f"  CV Doğruluğu   : %{cv_acc*100:.2f}")

results_df = pd.DataFrame(results).T.reset_index()
results_df.columns = ["Algoritma", "Test Doğruluğu (%)", "ROC-AUC (macro)", "CV Doğruluğu (%)"]
results_df = results_df.sort_values("Test Doğruluğu (%)", ascending=False)

print("\n" + "=" * 60)
print("SONUÇ TABLOSU (SIRALAMA)")
print("=" * 60)
print(results_df.to_string(index=False))

# 7. EN İYİ MODEL: RANDOM FOREST — DETAYLI ANALİZ
best_model  = models["Random Forest"]
y_pred_rf   = best_model.predict(X_test)
cm          = confusion_matrix(y_test, y_pred_rf)

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Karmaşıklık Matrisi
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=axes[0],
            xticklabels=["0 Kişi","1 Kişi","2 Kişi","3 Kişi"],
            yticklabels=["0 Kişi","1 Kişi","2 Kişi","3 Kişi"],
            linewidths=1, linecolor="white")
axes[0].set_title("Karmaşıklık Matrisi — Random Forest", fontsize=12, fontweight="bold")
axes[0].set_xlabel("Tahmin Edilen")
axes[0].set_ylabel("Gerçek")

# Öznitelik Önem Sıralaması
feat_imp = pd.Series(best_model.feature_importances_, index=X.columns).sort_values()
feat_imp.plot(kind="barh", ax=axes[1], color="#2196F3", edgecolor="navy")
axes[1].set_title("Öznitelik Önem Sıralaması", fontsize=12, fontweight="bold")
axes[1].set_xlabel("Önem Skoru")
axes[1].grid(axis="x", alpha=0.4)

plt.tight_layout()
plt.savefig("rf_analiz.png", dpi=150, bbox_inches="tight")
plt.show()
print("[✓] Görsel kaydedildi: rf_analiz.png")

# 8. ROC EĞRİSİ — Her sınıf için ayrı (Random Forest)
y_test_bin = label_binarize(y_test, classes=classes)   # (n, 4) binary matrix
y_prob_rf  = best_model.predict_proba(X_test)

fig, ax = plt.subplots(figsize=(9, 7))
roc_colors = ["#2196F3", "#4CAF50", "#FF9800", "#F44336"]

for i, (cls, col) in enumerate(zip(classes, roc_colors)):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob_rf[:, i])
    auc = roc_auc_score(y_test_bin[:, i], y_prob_rf[:, i])
    ax.plot(fpr, tpr, lw=2, color=col, label=f"{cls} Kişi (AUC={auc:.3f})")

ax.plot([0,1],[0,1], "k--", lw=1.2, label="Rastgele Sınıflandırıcı")
ax.set_xlabel("Yanlış Pozitif Oranı (FPR)", fontsize=11)
ax.set_ylabel("Doğru Pozitif Oranı (TPR)", fontsize=11)
ax.set_title("ROC Eğrisi — Random Forest (Sınıf Bazında)", fontsize=13, fontweight="bold")
ax.legend(loc="lower right", fontsize=10)
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("roc_egrisi.png", dpi=150, bbox_inches="tight")
plt.show()
print("[✓] Görsel kaydedildi: roc_egrisi.png")

# 9. ALGORİTMA KARŞILAŞTIRMA ÇUBUĞU
fig, ax = plt.subplots(figsize=(12, 6))
bar_colors = ["#1976D2" if r >= 98 else "#64B5F6" if r >= 90 else "#BBDEFB"
              for r in results_df["Test Doğruluğu (%)"]]
bars = ax.barh(results_df["Algoritma"], results_df["Test Doğruluğu (%)"],
               color=bar_colors, edgecolor="navy", height=0.6)
for bar, val in zip(bars, results_df["Test Doğruluğu (%)"]):
    ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height() / 2,
            f"%{val:.2f}", va="center", fontsize=10)
ax.set_xlim(50, 107)
ax.set_xlabel("Test Doğruluğu (%)", fontsize=11)
ax.set_title("Algoritma Performans Karşılaştırması", fontsize=13, fontweight="bold")
ax.axvline(x=95, color="red", linestyle="--", alpha=0.5, label="95% eşik")
ax.legend()
ax.grid(axis="x", alpha=0.3)
plt.tight_layout()
plt.savefig("algoritma_karsilastirma.png", dpi=150, bbox_inches="tight")
plt.show()
print("[✓] Görsel kaydedildi: algoritma_karsilastirma.png")

# 10. SINIFLANDIRMA RAPORU
print("\n" + "=" * 60)
print("RANDOM FOREST — SINIFLANDIRMA RAPORU")
print("=" * 60)
print(classification_report(y_test, y_pred_rf,
      target_names=["0 Kişi", "1 Kişi", "2 Kişi", "3 Kişi"]))

print("\n[✓] Analiz tamamlandı!")